### PR TITLE
Add IBAN details from ISO 13616-1

### PR DESCRIPTION
**Pull request by greysteil**
Support looking up the IBAN country code of the country, as detailed in ISO 13616-1.

### CODE REVIEW

**Comment by vjt** [comment]
Looks nice and clean to me.

**Comment by greysteil** [comment]
Thanks @vjt. @alexrabarts - what say you? We're big fans of this gem, btw.

**Comment by alexrabarts** [comment]
Looks good. I'll push this out in a new release shortly.

**Comment by greysteil** [comment]
Thanks @alexrabarts. Any news on that new version?

**Comment by alexrabarts** [comment]
Sorry for the delay. Your changes are in version 0.7.0, which is now on RubyGems. Thanks for the input.

**Comment by greysteil** [comment]
Awesome, thanks!

**Comment by alexrabarts** [comment]
@greysteil Since you are actively using this gem, I've added you as a collaborator.

**Comment by greysteil** [comment]
Nice, thanks @alexrabarts.

**Pull request merged**
