### PR TITLE
Allowed internationalization of country names

### PR DESCRIPTION
**Pull request by moret**
Hi. I was looking for the list of countries in Portuguese in a convenient way as you did but couldn't find one, so I built a list myself and added via I18n to your project. Hope you like it. Bye!

### CODE REVIEW

**Comment by dmke** [comment]
:+1: I like it, though I would leverage the translation work to [i18n_data](https;//github.com/grosser/i18n_data).

**Comment by moret** [comment]
Hi @alexrabarts . Would you like me to make another pull request without the conflicts, fix this one or just drop it? 8)

**Comment by greysteil** [comment]
Hi @moret, sorry for leaving this PR hanging. I'm going to close because you'd be better off using this gem and https://github.com/onomojo/i18n-country-translations together - that's what we do at GoCardless.

**Comment by moret** [comment]
No problem. I'm going to check out [i18n-country-translations](https://github.com/onomojo/i18n-country-translations), sounds like it's a perfect match for my needs too. 8)

**Pull request closed without merging**
